### PR TITLE
config: fix atlantis mainnet block number

### PR DESCRIPTION
**Pull request by soc1c**
we should not release any fork-block number unless there is one agreed upon.

### CODE REVIEW

**Comment by soc1c** [comment]
I have no clue why this fails now

**Comment by GregTheGreek** [comment]
@austinabell @steviezhang

**Comment by meowsbits** [comment]
Tests failure possibly rel https://github.com/eth-classic/go-ethereum/issues/66
Also possibly rel #67

**Comment by meowsbits** [comment]
Although I have a feeling that 

```
--- FAIL: TestAccumulateRewards1 (0.00s)
    state_processor_test.go:270: Unexpected era value, want 1 < e < 5, got: 430
--- FAIL: TestAccumulateRewards2_2Uncles (0.00s)
    state_processor_test.go:270: Unexpected era value, want 1 < e < 5, got: 430
--- FAIL: TestAccumulateRewards3_1Uncle (0.00s)
    state_processor_test.go:270: Unexpected era value, want 1 < e < 5, got: 430
--- FAIL: TestAccumulateRewards4_0Uncles (0.00s)
    state_processor_test.go:270: Unexpected era value, want 1 < e < 5, got: 430
FAIL
```

is just a bad test...

> https://circleci.com/gh/eth-classic/go-ethereum/415?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by austinabell** [comment]
AccumulateRewards tests fail due to the clause in `state_processor_test.go`:
```
// expectedEraFromBlockNumber is similar to GetBlockEra, but it
// returns a 1-indexed version of the number of type expectedEraForTesting
func expectedEraFromBlockNumber(i, eralen *big.Int, t *testing.T) expectedEraForTesting {
	e := GetBlockEra(i, eralen)
	ePlusOne := new(big.Int).Add(e, big.NewInt(1)) // since expectedEraForTesting is not 0-indexed; iota + 1
	ei := ePlusOne.Int64()
	expEra := int(ei)
	if expEra > 4 || expEra < 1 {
		t.Fatalf("Unexpected era value, want 1 < e < 5, got: %d", expEra)
	}
	return expectedEraForTesting(expEra)
}
```

just because it is expecting a certain era for testing

Other tests are failing because there is one final test in the TestCalcDifficulty1{Mainnet, Morden} tests that the block number is less than the number you are changing the config to:

```
big.NewInt(10000000): calcDifficultyAtlantis(time, &types.Header{Number: big.NewInt(10000000), Time: new(big.Int).SetUint64(parentTime), Difficulty: parentDiff}),
```

both are just existing tests that are not set up well and I had previously pushed back the block number in the test when I set the config to 8500000 for the difficulty tests

**Review by noot — APPROVED** [review]

**Review by austinabell — APPROVED** [review]

**Comment by meowsbits** [comment]
are we wanting to remove https://github.com/eth-classic/go-ethereum/pull/63/commits/f1b5ab5f545b25c31cc4e0d1f7fb6ea288518bbe, or ignore (since included w/ #73) if we'll squash on merge?

**Comment by GregTheGreek** [comment]
@soc1c can you rebase to include changes from #73

**Comment by soc1c** [comment]
it's already rebased and the checks passed

**Review by GregTheGreek — APPROVED** [review]

**Pull request merged**
