### PR TITLE
Tests config fix

### PR DESCRIPTION
**Pull request by austinabell**
Some tests are setup poorly (and still are) but this is a sufficient fix to allow #63 to work.

### CODE REVIEW

**Review by meowsbits — APPROVED** [review]

**Review by soc1c — APPROVED** [review]
Thanks

**Review by GregTheGreek — APPROVED** [review]

**Comment by meowsbits** [comment]
My only nit is that I would like to see these changes of this kind broken into more atomic commits in the future... for example, 

```
	if defuseBlock == nil {
	if atlantisBlock == nil {
		t.Error("missing Atlantis fork block")
	}

```

is a different idea than

```
		big.NewInt(10000000): calcDifficultyAtlantis(time, &types.Header{Number: big.NewInt(10000000), Time: new(big.Int).SetUint64(parentTime), Difficulty: parentDiff}),
		new(big.Int).Add(atlantisBlock, big.NewInt(1000000)): calcDifficultyAtlantis(time, &types.Header{Number: new(big.Int).Add(atlantisBlock, big.NewInt(1000000)), Time: new(big.Int).SetUint64(parentTime), Difficulty: parentDiff}),
	}
```
or
```
	if expEra > 4 || expEra < 1 {
		t.Fatalf("Unexpected era value, want 1 < e < 5, got: %d", expEra)
	}
```

But afaiu the changes as they are (as a whole) are OK, albeit presented as a 'fix everything'-type commit.

**Comment by meowsbits** [comment]
Damn, another nagging nit... the commit message should be prefixed with the package modified per Go convention.

**Comment by meowsbits** [comment]
~~Also worth documenting that this PR is a necessary prequel to #63.~~
Ah, nm, done w/ https://github.com/eth-classic/go-ethereum/pull/73#issue-289344163

**Comment by soc1c** [comment]
>  the commit message should be prefixed with the package modified per Go convention.

I'm not super sold on that, but I would also encourage more descriptive PR titles as they go into the release notes, ideally.

**Comment by austinabell** [comment]
> My only nit is that I would like to see these changes of this kind broken into more atomic commits in the future... for example,
> 
> ```
> 	if defuseBlock == nil {
> 	if atlantisBlock == nil {
> 		t.Error("missing Atlantis fork block")
> 	}
> ```
> 
> is a different idea than
> 
> ```
> 		big.NewInt(10000000): calcDifficultyAtlantis(time, &types.Header{Number: big.NewInt(10000000), Time: new(big.Int).SetUint64(parentTime), Difficulty: parentDiff}),
> 		new(big.Int).Add(atlantisBlock, big.NewInt(1000000)): calcDifficultyAtlantis(time, &types.Header{Number: new(big.Int).Add(atlantisBlock, big.NewInt(1000000)), Time: new(big.Int).SetUint64(parentTime), Difficulty: parentDiff}),
> 	}
> ```
> 
> or
> 
> ```
> 	if expEra > 4 || expEra < 1 {
> 		t.Fatalf("Unexpected era value, want 1 < e < 5, got: %d", expEra)
> 	}
> ```
> 
> But afaiu the changes as they are (as a whole) are OK, albeit presented as a 'fix everything'-type commit.

The PR is tests config fix, that conditional is explicitly a testing config check, do you believe it is out of the scope of these other changes?

**Comment by GregTheGreek** [comment]
> My only nit is that I would like to see these changes of this kind broken into more atomic commits in the future... for example,

I can back this.

> the commit message should be prefixed with the package modified per Go convention.

Not sure I agree with this at all.

> but I would also encourage more descriptive PR titles as they go into the release notes, ideally.

Yes @austinabell lets work on this

**Review by noot — APPROVED** [review]

**Comment by meowsbits** [comment]
w/r/t commit message prefixing, i don't feel super strongly about it either. here's where i got that idea:

- https://github.com/golang/go/wiki/CommitMessage
- it's how ethereum/go-ethereum and multi-geth do it usually
- for a project housing 90+ (?) packages it kinda seems useful sometimes

what i do feel strongly about is the one commit::one idea pattern (as above) https://secure.phabricator.com/book/phabflavor/article/recommendations_on_revision_control/

**Comment by GregTheGreek** [comment]
> w/r/t commit message prefixing, i don't feel super strongly about it either. here's where i got that idea:
> 
> * https://github.com/golang/go/wiki/CommitMessage
> * it's how ethereum/go-ethereum and multi-geth do it usually
> * for a project housing 40+ (?) packages it kinda seems useful sometimes

Yeah, I've seen this pattern before, either way we are squashing and merging, so if the PR title had that then we're good. IMO.

> what i do feel strongly about is the one commit::one idea pattern (as above) https://secure.phabricator.com/book/phabflavor/article/recommendations_on_revision_control/

I'm with you on this

**Comment by meowsbits** [comment]
are we waiting for a revised vc history or alright to move forward? For me, ok to merge as-is and get on with our lives :joy_cat:

**Comment by GregTheGreek** [comment]
lol didn't notice

**Pull request merged**
